### ISSUE TITLE
Where to download the GTSRB dataset and corresponding files used in the code?

### ISSUE THREAD

**Issue by XiaofanQue2000** [lanfenghuanyu/Sill-Net#2]

**Comment by vibe-Chen** [comment]
Standard GTSRB dataset is [Here](https://benchmark.ini.rub.de/gtsrb_dataset.html).
~~Unfortunately I haven't found their standard template, which are required by the code.~~
~~If you have found please contact asap :)~~

Update 08/06/2021:
~~I've found [this](https://github.com/lanfenghuanyu/Sill-Net/files/6943434/template_ordered.zip) from a mod of some game ;P~~
~~Yet it might not be the official one, I sincerely hope this would help.~~
~~btw: I've failed to run this, and still checking for errors.~~

Update 2 08/10/2021:
All the official datasets are uploaded by the author, and this reply is (mostly)outdated.

**Comment by lanfenghuanyu** [comment]
We have released all the datasets.
