### ISSUE TITLE
Unable to untar train models

### ISSUE THREAD

**Issue by vibe-Chen** [lanfenghuanyu/Sill-Net#3]
When I tried to untar your [trained models](https://drive.google.com/drive/folders/1iQzZdFte8gcLtIZdDXASqpCgJLMnUCuP?usp=sharing), it's said that they arn't valid tar files.
There might be something wrong, including upload has been terminated before tar files being uploaded completely.

Edited 08/12/2021:
In addition, it seems that not all models are released(e.g. GTSRB-related).

**Comment by lanfenghuanyu** [comment]
The model files have to be read by io_util.py in the codes we guided (not to untar). We have detailed the training procedures of few-shot learning for your careful reading. 
GTSRB related models are not hard to reproduce by the complete codes we provided.
Thank you for your questions.
