### ISSUE TITLE
How to reproduce the result on CUB

### ISSUE THREAD

**Issue by detectRecog** [lanfenghuanyu/Sill-Net#4]
Hello, nice work! I notice that you have provided the CUB model. However, I can not find the code for reproducing results on CUB. Could you please provide the code relating to CUB dataset?

**Comment by tim-heuwinkel** [comment]
I would also be interested how to reproduce the results found in the paper for one/few shot learning, since the code does not seem to be supplied.

**Comment by lanfenghuanyu** [comment]
Thank you for your question. We have detailed the training procedures of few-shot learning for your careful reading. The original codes are released by previous works and we simply add lines of codes for feature augmentation.
